name: "Redis Persistent"
version: "7.2.4"
slug: "redis_persistent"
description: "Redis add-on with persistent local storage for Home Assistant"
url: "https://redis.io"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
ports:
  6379/tcp: 6379
map:
  - share:rw  # Redis hoiab oma andmebaasi ja konfiguratsioonifaile siia
options:
  requirepass: ""  # Redis parool
  maxmemory_policy: "noeviction"  # MÃ¤lupoliitika
schema:
  requirepass: str?
  maxmemory_policy: list(noeviction|allkeys-lru|volatile-lru|allkeys-random|volatile-random|volatile-ttl)
